/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "generala.h"

bool_t
xdr_manostruct (XDR *xdrs, manostruct *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, ( 5 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->dados, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->dados;
					i < 5; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, ( 5 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->dados, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->dados;
					i < 5; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->dados, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_puntajesstruct (XDR *xdrs, puntajesstruct *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  MAXJUGADORES )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->puntos, MAXJUGADORES,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->turnojugador))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->puntos;
					i < MAXJUGADORES; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->turnojugador);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  MAXJUGADORES )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->puntos, MAXJUGADORES,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->turnojugador))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->puntos;
					i < MAXJUGADORES; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->turnojugador = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->puntos, MAXJUGADORES,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->turnojugador))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mipuntajestruct (XDR *xdrs, mipuntajestruct *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, ( 11 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->categorias, 11,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->categorias;
					i < 11; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, ( 11 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->categorias, 11,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->categorias;
					i < 11; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->categorias, 11,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datosinicialesstruct (XDR *xdrs, datosinicialesstruct *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cantidadJugadores))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nroJugador))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mano (XDR *xdrs, mano *objp)
{
	register int32_t *buf;

	 if (!xdr_manostruct (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_puntajes (XDR *xdrs, puntajes *objp)
{
	register int32_t *buf;

	 if (!xdr_puntajesstruct (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mipuntaje (XDR *xdrs, mipuntaje *objp)
{
	register int32_t *buf;

	 if (!xdr_mipuntajestruct (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datosiniciales (XDR *xdrs, datosiniciales *objp)
{
	register int32_t *buf;

	 if (!xdr_datosinicialesstruct (xdrs, objp))
		 return FALSE;
	return TRUE;
}
