/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GENERALA_H_RPCGEN
#define _GENERALA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXJUGADORES 6

struct manostruct {
	int dados[5];
};
typedef struct manostruct manostruct;

struct puntajesstruct {
	int puntos[MAXJUGADORES];
	int turnojugador;
};
typedef struct puntajesstruct puntajesstruct;

struct mipuntajestruct {
	int categorias[11];
};
typedef struct mipuntajestruct mipuntajestruct;

typedef manostruct mano;

typedef puntajesstruct puntajes;

typedef mipuntajestruct mipuntaje;

#define GENERALA 0x200F0B01
#define VER1 1

#if defined(__STDC__) || defined(__cplusplus)
#define mostrardados 1
extern  void * mostrardados_1(mano *, CLIENT *);
extern  void * mostrardados_1_svc(mano *, struct svc_req *);
#define elegirdados 2
extern  mano * elegirdados_1(mano *, CLIENT *);
extern  mano * elegirdados_1_svc(mano *, struct svc_req *);
#define mostrarpuntajes 3
extern  void * mostrarpuntajes_1(puntajes *, CLIENT *);
extern  void * mostrarpuntajes_1_svc(puntajes *, struct svc_req *);
#define mostrarmipuntaje 4
extern  void * mostrarmipuntaje_1(mipuntaje *, CLIENT *);
extern  void * mostrarmipuntaje_1_svc(mipuntaje *, struct svc_req *);
#define elegirmano 5
extern  int * elegirmano_1(mipuntaje *, CLIENT *);
extern  int * elegirmano_1_svc(mipuntaje *, struct svc_req *);
#define fin 6
extern  void * fin_1(puntajes *, CLIENT *);
extern  void * fin_1_svc(puntajes *, struct svc_req *);
#define inicio 7
extern  void * inicio_1(int *, CLIENT *);
extern  void * inicio_1_svc(int *, struct svc_req *);
extern int generala_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mostrardados 1
extern  void * mostrardados_1();
extern  void * mostrardados_1_svc();
#define elegirdados 2
extern  mano * elegirdados_1();
extern  mano * elegirdados_1_svc();
#define mostrarpuntajes 3
extern  void * mostrarpuntajes_1();
extern  void * mostrarpuntajes_1_svc();
#define mostrarmipuntaje 4
extern  void * mostrarmipuntaje_1();
extern  void * mostrarmipuntaje_1_svc();
#define elegirmano 5
extern  int * elegirmano_1();
extern  int * elegirmano_1_svc();
#define fin 6
extern  void * fin_1();
extern  void * fin_1_svc();
#define inicio 7
extern  void * inicio_1();
extern  void * inicio_1_svc();
extern int generala_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_manostruct (XDR *, manostruct*);
extern  bool_t xdr_puntajesstruct (XDR *, puntajesstruct*);
extern  bool_t xdr_mipuntajestruct (XDR *, mipuntajestruct*);
extern  bool_t xdr_mano (XDR *, mano*);
extern  bool_t xdr_puntajes (XDR *, puntajes*);
extern  bool_t xdr_mipuntaje (XDR *, mipuntaje*);

#else /* K&R C */
extern bool_t xdr_manostruct ();
extern bool_t xdr_puntajesstruct ();
extern bool_t xdr_mipuntajestruct ();
extern bool_t xdr_mano ();
extern bool_t xdr_puntajes ();
extern bool_t xdr_mipuntaje ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GENERALA_H_RPCGEN */
